# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoRadioButton2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(692, 400)
        self.verticalLayout = QtWidgets.QLabel(Dialog)
        self.verticalLayout.setGeometry(QtCore.QRect(40, 30, 151, 16))
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QLabel(Dialog)
        self.verticalLayout_2.setGeometry(QtCore.QRect(40, 200, 181, 16))
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSelected = QtWidgets.QLabel(Dialog)
        self.labelSelected.setGeometry(QtCore.QRect(274, 310, 401, 20))
        self.labelSelected.setText("")
        self.labelSelected.setObjectName("labelSelected")
        self.radioButtonMedium = QtWidgets.QRadioButton(Dialog)
        self.radioButtonMedium.setGeometry(QtCore.QRect(30, 60, 95, 20))
        self.radioButtonMedium.setObjectName("radioButtonMedium")
        self.radioButtonLarge = QtWidgets.QRadioButton(Dialog)
        self.radioButtonLarge.setGeometry(QtCore.QRect(30, 90, 95, 20))
        self.radioButtonLarge.setObjectName("radioButtonLarge")
        self.radioButtonXL = QtWidgets.QRadioButton(Dialog)
        self.radioButtonXL.setGeometry(QtCore.QRect(30, 120, 95, 20))
        self.radioButtonXL.setObjectName("radioButtonXL")
        self.radioButtonXXL = QtWidgets.QRadioButton(Dialog)
        self.radioButtonXXL.setGeometry(QtCore.QRect(30, 150, 95, 20))
        self.radioButtonXXL.setObjectName("radioButtonXXL")
        self.radioButtonDebitCard = QtWidgets.QRadioButton(Dialog)
        self.radioButtonDebitCard.setGeometry(QtCore.QRect(30, 240, 151, 20))
        self.radioButtonDebitCard.setObjectName("radioButtonDebitCard")
        self.radioButtonNetBanking = QtWidgets.QRadioButton(Dialog)
        self.radioButtonNetBanking.setGeometry(QtCore.QRect(30, 280, 141, 20))
        self.radioButtonNetBanking.setObjectName("radioButtonNetBanking")
        self.radioButtonCashOnDelivery = QtWidgets.QRadioButton(Dialog)
        self.radioButtonCashOnDelivery.setGeometry(QtCore.QRect(30, 320, 141, 20))
        self.radioButtonCashOnDelivery.setObjectName("radioButtonCashOnDelivery")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.verticalLayout.setText(_translate("Dialog", " Choose your Shirt\n"
"SIze"))
        self.verticalLayout_2.setText(_translate("Dialog", " Choose your payment method"))
        self.radioButtonMedium.setText(_translate("Dialog", "M"))
        self.radioButtonLarge.setText(_translate("Dialog", "L"))
        self.radioButtonXL.setText(_translate("Dialog", "XL"))
        self.radioButtonXXL.setText(_translate("Dialog", "XXL"))
        self.radioButtonDebitCard.setText(_translate("Dialog", " Debit/Credit Card"))
        self.radioButtonNetBanking.setText(_translate("Dialog", "NetBanking"))
        self.radioButtonCashOnDelivery.setText(_translate("Dialog", "Cash On Delivery"))
